FROM confluentinc/cp-zookeeper:7.5.3

USER root

WORKDIR /etc/zookeeper

# Download JMX exporter
RUN wget https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.20.0/jmx_prometheus_javaagent-0.20.0.jar

COPY ./metrics ./metrics

CMD ["/etc/confluent/docker/run"]