FROM golang:alpine3.19 AS builder

RUN apk update && apk add --no-cache git
RUN apk add --no-cache make
#FROM golang:1.23 AS build
WORKDIR /go/src
 
COPY *.mod *.sum ./
RUN go mod download
COPY . .

ENV CGO_ENABLED=0
#RUN go build -o openapi .
RUN make api_local_build

FROM scratch AS runtime
COPY --from=builder /go/src/bin ./
EXPOSE 8080/tcp
ENTRYPOINT ["./api"]