// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger Potion maker - OpenAPI 3.0
 *
 * Сервис изготовления зелий
 *
 * API version: 1.0.0
 */

package openapi




type Parameters struct {

	Param1 string `json:"param1,omitempty"`

	Param2 string `json:"param2,omitempty"`
}

// AssertParametersRequired checks if the required fields are not zero-ed
func AssertParametersRequired(obj Parameters) error {
	return nil
}

// AssertParametersConstraints checks if the values respects the defined constraints
func AssertParametersConstraints(obj Parameters) error {
	return nil
}
